import { useState, useCallback, useEffect, useRef } from "react";

const API_KEY = "d70v4chr01ql6rg0ov1gd70v4chr01ql6rg0ov20";
const BASE = "https://finnhub.io/api/v1";

const POPULAR = [
  "AAPL","MSFT","GOOGL","AMZN","NVDA","META","TSLA","BRK-B","JPM","V",
  "JNJ","WMT","PG","MA","HD","KO","PEP","COST","NFLX","DIS",
  "AMD","CRM","ADBE","INTC","BA","NKE","UBER","SQ","SPOT","PYPL",
  "ORCL","CSCO","QCOM","TXN","AVGO","MU","AMAT","LRCX","KLAC","MRVL",
  "UNH","LLY","PFE","ABBV","MRK","TMO","ABT","DHR","BMY","AMGN",
  "BLK","GS","MS","AXP","SCHW","C","BAC","WFC","USB","PNC",
  "XOM","CVX","COP","SLB","EOG","MPC","PSX","VLO","OXY","DVN",
  "LMT","RTX","GD","NOC","GE","HON","CAT","DE","MMM","EMR",
  "DUOL","EL","ABNB","COIN","SHOP","MELI","NU","SE","GRAB","BABA",
];

const GURUS = [
  { name:"Warren Buffett", fund:"Berkshire Hathaway", value:"$298B", img:"\u{1F3DB}", holdings:["AAPL","BAC","AXP","KO","CVX","OXY","KHC","MCO","CB","DVA","AMZN","NU","ALLY","TMUS"] },
  { name:"Bill Ackman", fund:"Pershing Square", value:"$13.7B", img:"\u{1F3AF}", holdings:["GOOGL","HLT","CMG","BN","NKE","UBER","CP","LOW","QSR","MNST"] },
  { name:"Terry Smith", fund:"Fundsmith Equity", value:"$27B", img:"\u{1F1EC}\u{1F1E7}", holdings:["META","MSFT","V","IDXX","SPGI","EL","SYK","WAT","ADP","FICO"] },
  { name:"François Rochon", fund:"Giverny Capital", value:"$1.1B", img:"\u{1F341}", holdings:["BRK-B","GOOGL","META","V","MSFT","ADBE","FIVE","ROL","POOL","WSO","ORLY"] },
  { name:"Michael Burry", fund:"Scion Asset Mgmt", value:"$240M", img:"\u{1F525}", holdings:["BABA","JD","ESTC","OSCR","BKNG","HCA","SATS"] },
  { name:"Li Lu", fund:"Himalaya Capital", value:"$3.8B", img:"\u{1F3D4}", holdings:["BRK-A","GOOGL","MU","BABA","EWBC","BAM","APO"] },
  { name:"Bill Gates", fund:"Gates Foundation", value:"$47B", img:"\u{1F4BB}", holdings:["MSFT","BRK-B","WM","CNI","CAT","ECL","SCHW","WMT","FDX"] },
  { name:"Chuck Akre", fund:"Akre Capital", value:"$12B", img:"\u{1F985}", holdings:["AMZN","MA","MCO","ORLY","V","BRK-B","GOOGL","KKR","AMT"] },
  { name:"Dev Kantesaria", fund:"Valley Forge Cap.", value:"$2.5B", img:"\u{1F3F0}", holdings:["V","MA","MSFT","IDXX","SPGI","MCO","ADBE","ROP","NOW"] },
  { name:"Nick Sleep", fund:"Nomad (Legacy)", value:"Closed", img:"\u{1F4A4}", holdings:["AMZN","COST","BRK-A"] },
  { name:"Mohnish Pabrai", fund:"Pabrai Funds", value:"$600M", img:"\u{1F1EE}\u{1F1F3}", holdings:["BABA","GOOGL","FIAT"] },
  { name:"David Tepper", fund:"Appaloosa Mgmt", value:"$6.8B", img:"\u26A1", holdings:["NVDA","META","MSFT","AMZN","GOOGL","BABA","UBER","AMD","LLY"] },
  { name:"Seth Klarman", fund:"Baupost Group", value:"$27B", img:"\u{1F4D5}", holdings:["LBTYA","LBTYK","QRVO","INTC","VSAT","FOXA","EBAY","WBD"] },
  { name:"Guy Spier", fund:"Aquamarine Fund", value:"$300M", img:"\u{1F41F}", holdings:["BRK-B","GOOGL","MSFT","JNJ","AMZN","BAM"] },
  { name:"Howard Marks", fund:"Oaktree Capital", value:"$170B AUM", img:"\u{1F4D8}", holdings:["Credit","Distressed","Real Estate","Infra"] },
];

const TIPS = {
  fcf: "Free Cash Flow par action : le cash réellement généré par l'entreprise après investissements, divisé par le nombre d'actions. C'est le nerf de la valorisation DCF.",
  netDebt: "Dette Nette par action : dette totale moins la trésorerie, ramenée par action. Négatif = l'entreprise a plus de cash que de dettes.",
  wacc: "Weighted Average Cost of Capital : le taux de rendement minimum exigé par les investisseurs. Plus il est élevé, plus la fair value baisse.",
  growth: "Taux de croissance annuel estimé du FCF. Y1-5 = phase de croissance, Y6-10 = normalisation.",
  terminal: "Croissance terminale : rythme perpétuel après 10 ans. Doit rester sous le WACC. Typiquement 2-4%.",
  dilution: "Taux annuel de dilution (+) ou rachat (-) d'actions. Rachat = FCF/action augmente.",
  margin: "Marge de sécurité : décote sur la fair value pour se protéger des erreurs d'estimation. Benjamin Graham recommandait 25-30%.",
  pe: "Price/Earnings : combien le marché paie pour 1$ de bénéfice. Élevé = attentes de forte croissance.",
  pb: "Price/Book : ratio prix / valeur comptable. Sous 1 = décote sur actifs nets.",
  roic: "Return on Invested Capital : rentabilité des capitaux investis. Au-dessus de 15% = excellent.",
  divYield: "Rendement du dividende annuel rapporté au prix de l'action.",
  revPS: "Revenue per Share : chiffre d'affaires divisé par le nombre d'actions.",
};

const LIGHT = {
  bg:"#f5f3f0", card:"rgba(255,255,255,0.92)", border:"rgba(120,80,200,0.1)",
  accent:"#7c3aed", accentDim:"rgba(124,58,237,0.1)", accentGlow:"rgba(124,58,237,0.2)",
  green:"#16a34a", greenDim:"rgba(22,163,74,0.08)",
  red:"#dc2626", redDim:"rgba(220,38,38,0.08)",
  text:"#1a1128", dim:"#8b80a5", mid:"#5c5478",
  input:"rgba(245,243,240,0.9)", inputBorder:"rgba(120,80,200,0.15)", blue:"#4f46e5",
};
const DARK = {
  bg:"#05030e", card:"rgba(14,11,28,0.92)", border:"rgba(180,140,255,0.06)",
  accent:"#b388ff", accentDim:"rgba(179,136,255,0.12)", accentGlow:"rgba(179,136,255,0.3)",
  green:"#34d399", greenDim:"rgba(52,211,153,0.1)",
  red:"#f87171", redDim:"rgba(248,113,113,0.1)",
  text:"#ede8f5", dim:"#5c5478", mid:"#9990b3",
  input:"rgba(8,5,18,0.85)", inputBorder:"rgba(180,140,255,0.1)", blue:"#818cf8",
};

const ff=`'Outfit',system-ui,sans-serif`, mono=`'JetBrains Mono','Fira Code',monospace`;

async function apiFetch(u){try{const r=await fetch(u);if(!r.ok)return null;const d=await r.json();if(d?.error)return null;return d;}catch{return null;}}
async function searchTickers(q){const d=await apiFetch(`${BASE}/search?q=${q}&token=${API_KEY}`);if(!d?.result)return[];return d.result.filter(r=>r.type==="Common Stock"||r.type==="ADR"||r.type==="EQS").slice(0,8).map(r=>({symbol:r.symbol,name:r.description||""}));}
async function fetchConsensus(tk){const[rec,tgt]=await Promise.all([apiFetch(`${BASE}/stock/recommendation?symbol=${tk}&token=${API_KEY}`),apiFetch(`${BASE}/stock/price-target?symbol=${tk}&token=${API_KEY}`)]);return{rec:rec?.[0]||null,tgt:tgt||null};}
async function loadTicker(tk){const[q,p,f]=await Promise.all([apiFetch(`${BASE}/quote?symbol=${tk}&token=${API_KEY}`),apiFetch(`${BASE}/stock/profile2?symbol=${tk}&token=${API_KEY}`),apiFetch(`${BASE}/stock/metric?symbol=${tk}&metric=all&token=${API_KEY}`)]);if(!q?.c)return null;const m=f?.metric||{};const mc=(p?.marketCapitalization||0)*1e6;const sh=p?.shareOutstanding?p.shareOutstanding*1e6:null;let fcf=m.freeCashFlowPerShareTTM??m.freeCashFlowPerShareAnnual??null;let nd=null;if(m.netDebtAnnual!=null&&sh)nd=(m.netDebtAnnual*1e6)/sh;return{ticker:tk.toUpperCase(),name:p?.name||tk,currency:p?.currency||"USD",price:q.c,sector:p?.finnhubIndustry||"—",country:p?.country||"—",exchange:p?.exchange||"—",marketCap:mc,sharesOut:sh,fcfPS:fcf,netDebtPS:nd,roic:m.roiTTM!=null?m.roiTTM/100:null,pe:m.peTTM??m.peAnnual??null,pb:m.pbAnnual??null,divY:m.dividendYieldIndicatedAnnual!=null?m.dividendYieldIndicatedAnnual/100:null,revPS:m.revenuePerShareTTM??null,desc:p?.name?`${p.name} — ${p.finnhubIndustry||""}, ${p.country||""}. IPO: ${p.ipo||"—"}.`:"",logo:p?.logo||null};}

function fmtP(n,c="USD"){if(n==null||isNaN(n))return"—";return(c==="EUR"?"€":c==="GBP"?"£":"$")+Number(n).toFixed(2);}
function fmtN(n){return n==null||isNaN(n)?"—":Number(n).toFixed(2);}
function fmtB(n){if(n==null)return"—";const a=Math.abs(n);if(a>=1e12)return(n/1e12).toFixed(1)+"T";if(a>=1e9)return(n/1e9).toFixed(1)+"B";if(a>=1e6)return(n/1e6).toFixed(1)+"M";return n.toFixed(0);}
function fmtPc(n){return n==null||isNaN(n)?"—":(n*100).toFixed(1)+"%";}
function dcf({fcfPS,netDebtPS,wacc,g1,g2,tg,dil,mg}){const w=wacc/100,a=g1/100,b=g2/100,t=tg/100,d=dil/100;const pr=[];let c=fcfPS;for(let y=1;y<=10;y++){const g=y<=5?a:b;c=c*(1+g)/(1+d);pr.push({year:y,fcf:c,disc:c/Math.pow(1+w,y),g});}const s=pr.reduce((x,p)=>x+p.disc,0);const tv=w>t?(c*(1+t))/(w-t):c*25;const dtv=tv/Math.pow(1+w,10);const fv=s+dtv-(netDebtPS||0);return{pr,s,tv,dtv,fv,sv:fv*(1-mg/100)};}

function Star({size=24,color="#b388ff"}){return <svg width={size} height={size} viewBox="0 0 100 100" fill="none"><path d="M50 0 Q50.8 44 52 48 Q56 49.2 100 50 Q56 50.8 52 52 Q50.8 56 50 100 Q49.2 56 48 52 Q44 50.8 0 50 Q44 49.2 48 48 Q49.2 44 50 0Z" fill={color} opacity="0.85"/><path d="M50 15 Q50.4 46 51 49 Q54 49.6 85 50 Q54 50.4 51 51 Q50.4 54 50 85 Q49.6 54 49 51 Q46 50.4 15 50 Q46 49.6 49 49 Q49.6 46 50 15Z" fill={color} opacity="0.3"/><circle cx="50" cy="50" r="2.5" fill={color} opacity="0.7"/></svg>;}

function BG({dark}){const ref=useRef(null);useEffect(()=>{if(!ref.current)return;const cv=ref.current,cx=cv.getContext("2d");let id;const rz=()=>{cv.width=window.innerWidth;cv.height=window.innerHeight;};rz();window.addEventListener("resize",rz);const st=Array.from({length:dark?220:180},()=>({x:Math.random()*cv.width,y:Math.random()*cv.height,r:Math.random()*1.8+0.3,sp:Math.random()*0.12+0.02,ph:Math.random()*Math.PI*2,ps:Math.random()*0.008+0.003}));let sh=[];const dr=()=>{cx.clearRect(0,0,cv.width,cv.height);const sc=dark?"200,180,255":"120,60,200";st.forEach(s=>{s.ph+=s.ps;s.y+=s.sp;if(s.y>cv.height){s.y=0;s.x=Math.random()*cv.width;}cx.beginPath();cx.arc(s.x,s.y,s.r,0,Math.PI*2);cx.fillStyle=`rgba(${sc},${dark?0.4+Math.sin(s.ph)*0.45:0.35+Math.sin(s.ph)*0.3})`;cx.fill();});if(Math.random()<0.003&&sh.length<2)sh.push({x:Math.random()*cv.width,y:Math.random()*cv.height*0.4,vx:(Math.random()-0.3)*6,vy:Math.random()*3+2,l:1});sh=sh.filter(s=>{s.x+=s.vx;s.y+=s.vy;s.l-=0.015;if(s.l<=0)return false;cx.beginPath();cx.moveTo(s.x,s.y);cx.lineTo(s.x-s.vx*8,s.y-s.vy*8);cx.strokeStyle=`rgba(${dark?"179,136,255":"124,58,237"},${s.l*0.6})`;cx.lineWidth=1.2;cx.stroke();return true;});id=requestAnimationFrame(dr);};dr();return()=>{cancelAnimationFrame(id);window.removeEventListener("resize",rz);};},[dark]);return <div style={{position:"fixed",inset:0,zIndex:0,pointerEvents:"none"}}><style>{`@keyframes fadeIn{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}@keyframes slideUp{from{opacity:0;transform:translateY(30px)}to{opacity:1;transform:translateY(0)}}@keyframes pulse{0%,100%{opacity:.6}50%{opacity:1}}`}</style><canvas ref={ref} style={{position:"absolute",inset:0,width:"100%",height:"100%"}}/>{dark&&<><div style={{position:"absolute",top:"0%",left:"5%",width:700,height:700,borderRadius:"50%",background:"radial-gradient(ellipse,rgba(120,60,200,0.06) 0%,transparent 70%)",filter:"blur(80px)"}}/><div style={{position:"absolute",top:"40%",right:"0%",width:600,height:600,borderRadius:"50%",background:"radial-gradient(ellipse,rgba(179,136,255,0.05) 0%,transparent 70%)",filter:"blur(100px)"}}/></>}{!dark&&<><div style={{position:"absolute",top:"0%",left:"5%",width:700,height:700,borderRadius:"50%",background:"radial-gradient(ellipse,rgba(124,58,237,0.07) 0%,transparent 70%)",filter:"blur(80px)"}}/><div style={{position:"absolute",top:"40%",right:"0%",width:600,height:600,borderRadius:"50%",background:"radial-gradient(ellipse,rgba(168,85,247,0.05) 0%,transparent 70%)",filter:"blur(100px)"}}/><div style={{position:"absolute",bottom:"5%",left:"25%",width:700,height:700,borderRadius:"50%",background:"radial-gradient(ellipse,rgba(124,58,237,0.04) 0%,transparent 60%)",filter:"blur(120px)"}}/></>}</div>;}

function Tip({text,children}){const[s,setS]=useState(false);return <span style={{position:"relative",cursor:"help",borderBottom:"1px dotted currentColor"}} onMouseEnter={()=>setS(true)} onMouseLeave={()=>setS(false)} onClick={()=>setS(!s)}>{children}{s&&<div style={{position:"absolute",bottom:"calc(100% + 8px)",left:"50%",transform:"translateX(-50%)",width:280,background:"rgba(20,16,40,0.98)",border:"1px solid rgba(179,136,255,0.2)",borderRadius:12,padding:"12px 16px",fontSize:12,color:"#ede8f5",lineHeight:1.5,zIndex:100,boxShadow:"0 8px 32px rgba(0,0,0,0.6)",fontFamily:ff,fontWeight:400,pointerEvents:"none"}}>{text}</div>}</span>;}

function Inp({label,value,onChange,suffix,note,tip,C:T}){const[f,setF]=useState(false);return <div style={{flex:1,minWidth:120}}><label style={{fontSize:10,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:"0.1em",marginBottom:5,display:"block",fontFamily:ff}}>{tip?<Tip text={tip}>{label} ⓘ</Tip>:label}</label><div style={{position:"relative"}}><input type="number" step="any" value={value} onChange={e=>onChange(e.target.value)} placeholder="0" style={{width:"100%",boxSizing:"border-box",background:T.input,border:`1.5px solid ${f?T.accent:T.inputBorder}`,borderRadius:10,color:T.text,fontSize:15,fontFamily:mono,padding:"11px 14px",paddingRight:suffix?44:14,outline:"none",transition:"all .25s",boxShadow:f?`0 0 0 3px ${T.accentDim}`:"none"}} onFocus={()=>setF(true)} onBlur={()=>setF(false)}/>{suffix&&<span style={{position:"absolute",right:12,top:"50%",transform:"translateY(-50%)",color:T.dim,fontSize:11,fontFamily:mono,fontWeight:600}}>{suffix}</span>}</div>{note&&<div style={{fontSize:10,color:T.dim,marginTop:3}}>{note}</div>}</div>;}

function Crd({children,style:s,glow,anim,delay,C:T}){return <div style={{background:T.card,border:`1px solid ${T.border}`,borderRadius:16,padding:"22px 24px",marginBottom:16,backdropFilter:"blur(20px)",boxShadow:glow?`0 0 50px ${T.accentDim}`:"0 2px 16px rgba(0,0,0,0.12)",animation:anim?`slideUp .6s ease-out ${delay||"0s"} both`:"none",...s}}>{children}</div>;}
function Tag({children,color,C:T}){return <span style={{fontSize:10,fontWeight:600,padding:"3px 10px",borderRadius:6,background:color==="green"?T.greenDim:color==="red"?T.redDim:color==="blue"?"rgba(129,140,248,.1)":T.accentDim,color:color==="green"?T.green:color==="red"?T.red:color==="blue"?T.blue:T.accent,fontFamily:ff}}>{children}</span>;}
function Pill({label,value,color,C:T}){const bg=color==="green"?T.greenDim:color==="red"?T.redDim:T.accentDim;const fg=color==="green"?T.green:color==="red"?T.red:T.accent;return <div style={{background:bg,border:`1px solid ${fg}22`,borderRadius:12,padding:"12px 18px",flex:1,minWidth:100}}><div style={{fontSize:9,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:3,fontFamily:ff}}>{label}</div><div style={{fontSize:18,fontWeight:700,fontFamily:mono,color:fg}}>{value}</div></div>;}

function ConsBar({rec,tgt,C:T}){if(!rec&&!tgt)return null;const tot=rec?(rec.strongBuy||0)+(rec.buy||0)+(rec.hold||0)+(rec.sell||0)+(rec.strongSell||0):0;return <Crd C={T} anim delay="0.05s"><div style={{fontSize:11,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:14}}>Consensus Analystes</div>{rec&&tot>0&&<div><div style={{display:"flex",gap:2,height:8,borderRadius:4,overflow:"hidden",marginBottom:10}}>{[{v:rec.strongBuy,c:"#22c55e"},{v:rec.buy,c:"#4ade80"},{v:rec.hold,c:"#fbbf24"},{v:rec.sell,c:"#f87171"},{v:rec.strongSell,c:"#dc2626"}].map((x,i)=>x.v>0?<div key={i} style={{flex:x.v,background:x.c}}/>:null)}</div><div style={{display:"flex",justifyContent:"space-between",fontSize:11,fontFamily:mono,flexWrap:"wrap",gap:4}}><span style={{color:T.green}}>Strong Buy {rec.strongBuy}</span><span style={{color:"#4ade80"}}>Buy {rec.buy}</span><span style={{color:"#fbbf24"}}>Hold {rec.hold}</span><span style={{color:T.red}}>Sell {rec.sell}</span><span style={{color:"#dc2626"}}>Strong Sell {rec.strongSell}</span></div></div>}{tgt?.targetMean&&<div style={{display:"flex",gap:12,marginTop:14,flexWrap:"wrap"}}>{[{l:"Target Bas",v:fmtP(tgt.targetLow),c:T.red},{l:"Target Moyen",v:fmtP(tgt.targetMean),c:T.accent},{l:"Target Haut",v:fmtP(tgt.targetHigh),c:T.green}].map(t=><div key={t.l} style={{background:T.input,borderRadius:10,padding:"10px 16px",border:`1px solid ${T.inputBorder}`,flex:1,minWidth:80,textAlign:"center"}}><div style={{fontSize:9,color:T.dim,textTransform:"uppercase"}}>{t.l}</div><div style={{fontSize:16,fontWeight:700,fontFamily:mono,color:t.c,marginTop:2}}>{t.v}</div></div>)}</div>}</Crd>;}

const PG={HOME:0,ANA:1,RES:2,WL:3,GU:4,ABT:5,SET:6};

export default function App(){
  const[dark,setDark]=useState(()=>{try{const v=localStorage.getItem("fh_theme");if(v==="light")return false;if(v==="dark")return true;const h=new Date().getHours();return h>=21||h<8;}catch{return true;}});
  const T=dark?DARK:LIGHT;
  useEffect(()=>{try{localStorage.setItem("fh_theme",dark?"dark":"light");}catch{}},[dark]);

  const[page,setPage]=useState(PG.HOME);const[query,setQuery]=useState("");const[sugg,setSugg]=useState([]);const[showS,setShowS]=useState(false);const[loading,setLoading]=useState(false);const[err,setErr]=useState("");const[data,setData]=useState(null);const[cons,setCons]=useState({rec:null,tgt:null});const[price,setPrice]=useState("");const[fcfPS,setFcfPS]=useState("");const[ndPS,setNdPS]=useState("");const[cur,setCur]=useState("USD");const[wacc,setWacc]=useState("10");const[g1,setG1]=useState("8");const[g2,setG2]=useState("5");const[tg,setTg]=useState("2.5");const[dil,setDil]=useState("0");const[mg,setMg]=useState("25");const[res,setRes]=useState(null);const[showTbl,setShowTbl]=useState(false);
  const[wl,setWl]=useState(()=>{try{return JSON.parse(localStorage.getItem("fh_wl"))||[];}catch{return[];}});
  const[cMsg,setCMsg]=useState("");const[cSent,setCSent]=useState(false);const[gS,setGS]=useState("");
  const sRef=useRef(null);
  useEffect(()=>{try{localStorage.setItem("fh_wl",JSON.stringify(wl));}catch{}},[wl]);
  useEffect(()=>{if(!query.trim()){setSugg([]);return;}const q=query.toUpperCase().trim();const l=POPULAR.filter(t=>t.startsWith(q)).slice(0,6).map(t=>({symbol:t,name:""}));setSugg(l);clearTimeout(sRef.current);if(query.length>=2)sRef.current=setTimeout(async()=>{const a=await searchTickers(q);if(a?.length){const m=[...l];a.forEach(r=>{if(!m.find(x=>x.symbol===r.symbol))m.push(r);});setSugg(m.slice(0,8));}},300);},[query]);

  const load=useCallback(async(tk)=>{const t=(tk||query).trim().toUpperCase();if(!t)return;setLoading(true);setErr("");setQuery(t);setShowS(false);setCons({rec:null,tgt:null});const[r,cn]=await Promise.all([loadTicker(t),fetchConsensus(t)]);if(r){setData(r);setCur(r.currency||"USD");setPrice(String(r.price||""));setFcfPS(r.fcfPS!=null?String(Number(r.fcfPS).toFixed(2)):"");setNdPS(r.netDebtPS!=null?String(Number(r.netDebtPS).toFixed(2)):"");setRes(null);setCons(cn||{rec:null,tgt:null});setPage(PG.ANA);if(r.fcfPS==null||r.netDebtPS==null)setErr("Certaines données manquent — complétez manuellement.");}else{setData({ticker:t,name:t,currency:"USD",price:null,sector:"—",country:"—",exchange:"—",marketCap:null,sharesOut:null,fcfPS:null,netDebtPS:null,roic:null,pe:null,pb:null,divY:null,revPS:null,desc:"",logo:null});setCur("USD");setPrice("");setFcfPS("");setNdPS("");setRes(null);setPage(PG.ANA);setErr("API indisponible — renseignez manuellement.");}setLoading(false);},[query]);

  const calc=useCallback(()=>{const f=parseFloat(fcfPS),w=parseFloat(wacc);if(!f||!w){setErr("FCF/share et WACC sont requis.");return;}setErr("");setRes(dcf({fcfPS:f,netDebtPS:parseFloat(ndPS)||0,wacc:w,g1:parseFloat(g1),g2:parseFloat(g2),tg:parseFloat(tg),dil:parseFloat(dil)||0,mg:parseFloat(mg)||0}));setShowTbl(true);setPage(PG.RES);},[fcfPS,ndPS,wacc,g1,g2,tg,dil,mg]);

  const addWl=()=>{if(!data||wl.find(w=>w.ticker===data.ticker))return;setWl(p=>[...p,{ticker:data.ticker,name:data.name,price:data.price,currency:data.currency,date:new Date().toLocaleDateString()}]);};
  const rmWl=(tk)=>setWl(p=>p.filter(w=>w.ticker!==tk));
  const reset=()=>{setQuery("");setData(null);setPrice("");setFcfPS("");setNdPS("");setRes(null);setShowTbl(false);setErr("");setCons({rec:null,tgt:null});setPage(PG.HOME);};
  const up=res&&price?((res.fv-parseFloat(price))/parseFloat(price)*100):null;
  const su=res&&price?((res.sv-parseFloat(price))/parseFloat(price)*100):null;
  const inWl=data&&wl.find(w=>w.ticker===data.ticker);

  const navs=[{l:"Analyse",p:PG.HOME,i:"✦"},{l:"Watchlist",p:PG.WL,i:"★"},{l:"Investisseurs",p:PG.GU,i:"👑"},{l:"Réglages",p:PG.SET,i:"⚙"},{l:"À propos",p:PG.ABT,i:"ℹ"}];
  const btnS={background:"transparent",border:`1px solid ${T.inputBorder}`,borderRadius:10,padding:"8px 18px",color:T.dim,fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:ff,transition:"all .2s"};

  return <div style={{minHeight:"100vh",background:T.bg,fontFamily:ff,color:T.text,transition:"background .4s, color .4s"}}>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet"/>
    <BG dark={dark}/>
    <div style={{position:"relative",zIndex:1}}>

    {/* HEADER */}
    <div style={{borderBottom:`1px solid ${T.border}`,padding:"14px 24px",display:"flex",alignItems:"center",justifyContent:"space-between",backdropFilter:"blur(24px)",background:dark?"rgba(5,3,14,0.75)":"rgba(245,243,240,0.8)",position:"sticky",top:0,zIndex:20}}>
      <div style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}} onClick={reset}>
        <div style={{width:36,height:36,borderRadius:11,background:`linear-gradient(135deg,${T.accent},#7c3aed)`,display:"flex",alignItems:"center",justifyContent:"center",boxShadow:`0 4px 18px ${T.accentDim}`}}><Star size={22} color={dark?"#05030e":"#fff"}/></div>
        <div><div style={{fontSize:16,fontWeight:700,letterSpacing:"-.03em"}}>Finheist</div><div style={{fontSize:8,color:T.dim,letterSpacing:".1em",textTransform:"uppercase"}}>Intrinsic Value Engine</div></div>
      </div>
      <div style={{display:"flex",gap:3,flexWrap:"wrap"}}>{navs.map(n=><button key={n.l} onClick={()=>{if(n.p===PG.HOME)reset();else setPage(n.p);}} style={{background:page===n.p||(page===PG.ANA||page===PG.RES)&&n.p===PG.HOME?T.accentDim:"transparent",border:`1px solid ${page===n.p?T.accent+"33":"transparent"}`,borderRadius:10,padding:"6px 12px",color:page===n.p?T.accent:T.dim,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:ff,transition:"all .2s",display:"flex",alignItems:"center",gap:4}}><span style={{fontSize:11}}>{n.i}</span>{n.l}</button>)}</div>
      {data&&(page===PG.ANA||page===PG.RES)&&<div style={{textAlign:"right"}}><div style={{fontSize:13,fontWeight:700}}>{data.name?.substring(0,22)}</div><div style={{fontSize:10,color:T.accent,fontFamily:mono}}>{data.ticker}</div></div>}
    </div>

    <div style={{maxWidth:720,margin:"0 auto",padding:"28px 20px 80px"}}>

    {/* HOME */}
    {page===PG.HOME&&<div style={{animation:"fadeIn .6s ease-out"}}>
      <div style={{textAlign:"center",padding:"80px 0 50px"}}>
        <div style={{display:"inline-flex",marginBottom:24}}><div style={{width:64,height:64,borderRadius:18,background:`linear-gradient(135deg,${T.accent},#7c3aed)`,display:"flex",alignItems:"center",justifyContent:"center",boxShadow:`0 8px 40px ${T.accentGlow}`}}><Star size={38} color={dark?"#05030e":"#fff"}/></div></div>
        <h1 style={{fontSize:34,fontWeight:700,letterSpacing:"-.04em",margin:0}}>Fin<span style={{color:T.accent}}>heist</span></h1>
        <p style={{color:T.dim,fontSize:14,marginTop:10,maxWidth:420,marginLeft:"auto",marginRight:"auto",lineHeight:1.6}}>Valeur intrinsèque per share · Données temps réel · Consensus analystes</p>
      </div>
      <Crd C={T} anim delay="0.1s" style={{overflow:"visible",position:"relative",zIndex:40}}><div style={{position:"relative"}}><div style={{display:"flex",gap:10}}><div style={{flex:1,position:"relative",zIndex:41}}><input type="text" value={query} onChange={e=>{setQuery(e.target.value.toUpperCase());setShowS(true);}} onFocus={()=>setShowS(true)} onKeyDown={e=>{if(e.key==="Enter")load();}} placeholder="AAPL, NVDA, ASML, DUOL..." style={{width:"100%",boxSizing:"border-box",background:T.input,border:`1.5px solid ${T.inputBorder}`,borderRadius:14,color:T.text,fontSize:18,fontFamily:mono,padding:"16px 20px",outline:"none",textTransform:"uppercase"}} onBlur={()=>setTimeout(()=>setShowS(false),200)}/>{showS&&sugg.length>0&&<div style={{position:"absolute",top:"calc(100% + 8px)",left:0,right:0,background:dark?"rgba(10,8,22,.98)":"rgba(255,255,255,.98)",border:`1px solid ${T.border}`,borderRadius:14,overflow:"hidden",zIndex:60,boxShadow:"0 16px 48px rgba(0,0,0,0.4)",maxHeight:300,overflowY:"auto"}}>{sugg.map((s,i)=><div key={s.symbol} onClick={()=>load(s.symbol)} style={{padding:"12px 18px",cursor:"pointer",display:"flex",justifyContent:"space-between",borderBottom:i<sugg.length-1?`1px solid ${T.border}`:"none",transition:"background .15s"}} onMouseOver={e=>e.currentTarget.style.background=T.accentDim} onMouseOut={e=>e.currentTarget.style.background="transparent"}><div><span style={{fontFamily:mono,fontWeight:700,fontSize:14,color:T.accent}}>{s.symbol}</span>{s.name&&<span style={{color:T.mid,fontSize:12,marginLeft:10}}>{s.name.substring(0,35)}</span>}</div><span style={{color:T.dim}}>→</span></div>)}</div>}</div><button onClick={()=>load()} disabled={loading} style={{background:`linear-gradient(135deg,${T.accent},#7c3aed)`,border:"none",borderRadius:14,color:dark?"#05030e":"#fff",fontWeight:700,fontSize:15,padding:"0 32px",cursor:loading?"wait":"pointer",fontFamily:ff,boxShadow:`0 4px 20px ${T.accentDim}`,minWidth:120}}>{loading?"...":"Analyser"}</button></div>{err&&<div style={{marginTop:12,fontSize:12,color:T.red}}>{err}</div>}</div></Crd>
      <Crd C={T} anim delay="0.2s" style={{position:"relative",zIndex:1}}><div style={{fontSize:10,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".12em",marginBottom:12}}>Accès rapide</div><div style={{display:"flex",flexWrap:"wrap",gap:6}}>{POPULAR.slice(0,20).map(t=><button key={t} onClick={()=>load(t)} style={{background:T.input,border:`1px solid ${T.inputBorder}`,borderRadius:8,padding:"7px 14px",cursor:"pointer",color:T.mid,fontSize:12,fontFamily:mono,fontWeight:600,transition:"all .2s"}} onMouseOver={e=>{e.target.style.borderColor=T.accent;e.target.style.color=T.accent;e.target.style.background=T.accentDim;}} onMouseOut={e=>{e.target.style.borderColor=T.inputBorder;e.target.style.color=T.mid;e.target.style.background=T.input;}}>{t}</button>)}</div></Crd>
    </div>}

    {/* ANALYSIS */}
    {page===PG.ANA&&data&&<div style={{animation:"fadeIn .5s ease-out"}}>
      {/* Top buttons */}
      <div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><button onClick={reset} style={btnS}>← Retour</button><button onClick={()=>{reset();}} style={btnS}>Autre action ↻</button></div>
      <Crd C={T} anim delay="0s" style={{background:dark?`linear-gradient(135deg,rgba(179,136,255,.06),rgba(179,136,255,.01))`:`linear-gradient(135deg,rgba(124,58,237,.04),rgba(124,58,237,.01))`,border:`1px solid ${dark?"rgba(179,136,255,.12)":"rgba(124,58,237,.1)"}`}}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",gap:14}}>
          <div><h2 style={{fontSize:22,fontWeight:700,margin:"0 0 6px"}}>{data.name}</h2><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:8}}><Tag C={T}>{data.ticker}</Tag><Tag C={T} color="blue">{data.exchange}</Tag>{data.sector!=="—"&&<Tag C={T}>{data.sector}</Tag>}</div>{data.desc&&<p style={{fontSize:11,color:T.dim,lineHeight:1.5,maxWidth:400,margin:0}}>{data.desc.substring(0,180)}</p>}</div>
          <div style={{textAlign:"right"}}><div style={{fontSize:30,fontWeight:700,fontFamily:mono,color:T.accent}}>{fmtP(data.price,cur)}</div><div style={{fontSize:11,color:T.dim}}>Cap: {fmtB(data.marketCap)}</div><button onClick={addWl} style={{marginTop:8,background:inWl?T.greenDim:T.accentDim,border:`1px solid ${inWl?T.green+"33":T.accent+"33"}`,borderRadius:8,padding:"5px 12px",color:inWl?T.green:T.accent,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:ff}}>{inWl?"✓ Watchlist":"+ Watchlist"}</button></div>
        </div>
        <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:16}}>{[{l:"P/E",v:data.pe!=null?Number(data.pe).toFixed(1):"—",t:TIPS.pe},{l:"P/B",v:data.pb!=null?Number(data.pb).toFixed(1):"—",t:TIPS.pb},{l:"ROIC",v:fmtPc(data.roic),t:TIPS.roic},{l:"Div.",v:data.divY!=null?fmtPc(data.divY):"—",t:TIPS.divYield},{l:"Rev/sh",v:data.revPS!=null?fmtP(data.revPS,cur):"—",t:TIPS.revPS}].map(r=><div key={r.l} style={{background:T.input,borderRadius:10,padding:"10px 16px",border:`1px solid ${T.inputBorder}`,flex:1,minWidth:70,textAlign:"center"}}><Tip text={r.t}><div style={{fontSize:9,color:T.dim,textTransform:"uppercase"}}>{r.l} ⓘ</div></Tip><div style={{fontSize:14,fontWeight:700,fontFamily:mono,marginTop:2}}>{r.v}</div></div>)}</div>
      </Crd>
      <ConsBar rec={cons.rec} tgt={cons.tgt} C={T}/>
      <Crd C={T} anim delay="0.1s"><div style={{fontSize:11,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:14,display:"flex",alignItems:"center",gap:6}}><span style={{width:6,height:6,borderRadius:"50%",background:T.green,display:"inline-block",animation:"pulse 2s ease-in-out infinite"}}/>Métriques Per Share · Live</div><div style={{display:"flex",gap:14,flexWrap:"wrap"}}><Inp C={T} label={`Prix (${cur})`} value={price} onChange={setPrice} suffix={cur==="EUR"?"€":"$"}/><Inp C={T} label="FCF / Action" value={fcfPS} onChange={setFcfPS} suffix={cur==="EUR"?"€":"$"} tip={TIPS.fcf}/><Inp C={T} label="Dette Nette / Action" value={ndPS} onChange={setNdPS} suffix={cur==="EUR"?"€":"$"} note="Négatif = trésorerie nette" tip={TIPS.netDebt}/></div></Crd>
      <Crd C={T} anim delay="0.15s"><div style={{fontSize:11,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:14}}>Paramètres DCF</div><div style={{display:"flex",gap:14,flexWrap:"wrap"}}><Inp C={T} label="WACC" value={wacc} onChange={setWacc} suffix="%" tip={TIPS.wacc}/><Inp C={T} label="Croissance Y1-5" value={g1} onChange={setG1} suffix="%" tip={TIPS.growth}/><Inp C={T} label="Croissance Y6-10" value={g2} onChange={setG2} suffix="%" tip={TIPS.growth}/><Inp C={T} label="Croissance terminale" value={tg} onChange={setTg} suffix="%" tip={TIPS.terminal}/></div></Crd>
      <Crd C={T} anim delay="0.2s"><div style={{display:"flex",gap:20,flexWrap:"wrap"}}><div style={{flex:1,minWidth:200}}><label style={{fontSize:10,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:5,display:"block"}}><Tip text={TIPS.dilution}>Dilution / Rachat ⓘ</Tip></label><div style={{position:"relative"}}><input type="number" step="0.5" value={dil} onChange={e=>setDil(e.target.value)} style={{width:"100%",boxSizing:"border-box",background:T.input,border:`1.5px solid ${T.inputBorder}`,borderRadius:10,color:T.text,fontSize:15,fontFamily:mono,padding:"11px 44px 11px 14px",outline:"none"}}/><span style={{position:"absolute",right:12,top:"50%",transform:"translateY(-50%)",color:T.dim,fontSize:11,fontFamily:mono}}>%/an</span></div><div style={{marginTop:6,fontSize:11,fontFamily:mono,color:parseFloat(dil)<0?T.green:parseFloat(dil)>0?T.red:T.dim}}>{parseFloat(dil)<0?"✦ Buyback — FCF/action augmente":parseFloat(dil)>0?"⚠ Dilution — FCF/action diminue":"— Neutre"}</div></div><div style={{flex:1,minWidth:200}}><label style={{fontSize:10,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:5,display:"block"}}><Tip text={TIPS.margin}>Marge de sécurité ⓘ</Tip></label><input type="range" min="0" max="50" step="5" value={mg} onChange={e=>setMg(e.target.value)} style={{width:"100%",accentColor:T.accent,marginTop:10,cursor:"pointer"}}/><div style={{display:"flex",justifyContent:"space-between",marginTop:6}}><span style={{fontSize:10,color:T.dim}}>0%</span><span style={{fontSize:18,fontWeight:700,color:T.accent,fontFamily:mono}}>{mg}%</span><span style={{fontSize:10,color:T.dim}}>50%</span></div></div></div></Crd>
      {err&&<div style={{fontSize:13,color:T.red,marginBottom:12}}>{err}</div>}
      <button onClick={calc} style={{width:"100%",padding:"16px",border:"none",borderRadius:14,background:`linear-gradient(135deg,${T.accent},#7c3aed)`,color:dark?"#05030e":"#fff",fontSize:16,fontWeight:700,cursor:"pointer",fontFamily:ff,boxShadow:`0 6px 30px ${T.accentGlow}`,display:"flex",alignItems:"center",justifyContent:"center",gap:8,transition:"transform .15s"}} onMouseOver={e=>e.currentTarget.style.transform="translateY(-2px)"} onMouseOut={e=>e.currentTarget.style.transform="translateY(0)"}><Star size={18} color={dark?"#05030e":"#fff"}/>Calculer la Valeur Intrinsèque</button>
    </div>}

    {/* RESULTS */}
    {page===PG.RES&&res&&data&&<div style={{animation:"fadeIn .5s ease-out"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><button onClick={()=>setPage(PG.ANA)} style={btnS}>← Modifier</button><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:15,fontWeight:700}}>{data.name?.substring(0,20)}</span><Tag C={T}>{data.ticker}</Tag></div><button onClick={reset} style={btnS}>Autre action ↻</button></div>
      <Crd C={T} glow anim delay="0s" style={{textAlign:"center",padding:"36px 24px",background:dark?`linear-gradient(135deg,rgba(179,136,255,.1),rgba(179,136,255,.02))`:`linear-gradient(135deg,rgba(124,58,237,.06),rgba(124,58,237,.01))`,border:`1px solid ${dark?"rgba(179,136,255,.18)":"rgba(124,58,237,.12)"}`}}><div style={{fontSize:10,color:T.dim,textTransform:"uppercase",letterSpacing:".15em",marginBottom:8}}>Valeur Intrinsèque / Action</div><div style={{fontSize:48,fontWeight:700,fontFamily:mono,color:T.accent,lineHeight:1}}>{fmtP(res.fv,cur)}</div>{up!==null&&<div style={{fontSize:15,marginTop:12,fontFamily:mono,fontWeight:600,color:up>0?T.green:T.red}}>{up>0?"▲":"▼"} {Math.abs(up).toFixed(1)}% vs {fmtP(parseFloat(price),cur)}</div>}<div style={{display:"flex",gap:12,justifyContent:"center",marginTop:24,flexWrap:"wrap"}}><div style={{background:T.input,borderRadius:12,padding:"14px 24px",border:`1px solid ${T.inputBorder}`}}><div style={{fontSize:9,color:T.dim,textTransform:"uppercase"}}>Avec marge {mg}%</div><div style={{fontSize:22,fontWeight:700,fontFamily:mono,color:su>0?T.green:T.red}}>{fmtP(res.sv,cur)}</div></div><div style={{background:T.input,borderRadius:12,padding:"14px 24px",border:`1px solid ${T.inputBorder}`}}><div style={{fontSize:9,color:T.dim,textTransform:"uppercase"}}>Σ DCF / action</div><div style={{fontSize:22,fontWeight:700,fontFamily:mono}}>{fmtP(res.s,cur)}</div></div><div style={{background:T.input,borderRadius:12,padding:"14px 24px",border:`1px solid ${T.inputBorder}`}}><div style={{fontSize:9,color:T.dim,textTransform:"uppercase"}}>Terminal / action</div><div style={{fontSize:22,fontWeight:700,fontFamily:mono}}>{fmtP(res.dtv,cur)}</div></div></div></Crd>
      <div style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:16}}><Pill C={T} label="Signal" value={su>0?"ACHAT":su>-15?"NEUTRE":"SURVALORISÉ"} color={su>0?"green":su>-15?null:"red"}/><Pill C={T} label="Upside Fair" value={(up>0?"+":"")+(up?.toFixed(1)||"—")+"%"} color={up>0?"green":"red"}/><Pill C={T} label="Upside Safe" value={(su>0?"+":"")+(su?.toFixed(1)||"—")+"%"} color={su>0?"green":"red"}/></div>
      {price&&<Crd C={T} anim delay="0.15s"><div style={{fontSize:11,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:18}}>Comparaison Visuelle</div>{[{l:"Prix Actuel",v:parseFloat(price),c:T.mid},{l:`Avec Marge ${mg}%`,v:res.sv,c:T.accent},{l:"Fair Value",v:res.fv,c:T.green}].map(b=>{const mx=Math.max(parseFloat(price),res.fv,res.sv,1)*1.15;return<div key={b.l} style={{marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:5}}><span style={{fontSize:11,color:T.dim}}>{b.l}</span><span style={{fontSize:14,fontFamily:mono,fontWeight:600,color:b.c}}>{fmtP(b.v,cur)}</span></div><div style={{height:8,background:T.input,borderRadius:4,overflow:"hidden"}}><div style={{width:Math.max(0,Math.min(100,b.v/mx*100))+"%",height:"100%",background:`linear-gradient(90deg,${b.c},${b.c}88)`,borderRadius:4,transition:"width 1s cubic-bezier(.16,1,.3,1)"}}/></div></div>;})}</Crd>}
      <Crd C={T} anim delay="0.2s"><div onClick={()=>setShowTbl(!showTbl)} style={{display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer",userSelect:"none"}}><div style={{fontSize:11,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em"}}>Projections 10 Ans</div><span style={{fontSize:20,color:T.dim,transition:"transform .3s",transform:showTbl?"rotate(180deg)":"rotate(0)"}}>▾</span></div>{showTbl&&<div style={{marginTop:14,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontFamily:mono,fontSize:12}}><thead><tr style={{borderBottom:`1px solid ${T.border}`}}>{["Année","Croiss.","FCF/sh","Actualisé","Cumul"].map(h=><th key={h} style={{padding:"8px 10px",textAlign:"right",color:T.dim,fontWeight:600,fontSize:9,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{res.pr.map((p,i)=>{const cm=res.pr.slice(0,i+1).reduce((x,y)=>x+y.disc,0);return<tr key={p.year} style={{borderBottom:`1px solid ${T.border}22`}}><td style={{padding:"7px 10px",textAlign:"right",color:T.mid}}>Y{p.year}</td><td style={{padding:"7px 10px",textAlign:"right",color:p.g>=0?T.green:T.red}}>{(p.g*100).toFixed(1)}%</td><td style={{padding:"7px 10px",textAlign:"right",color:T.text}}>{fmtN(p.fcf)}</td><td style={{padding:"7px 10px",textAlign:"right",color:T.accent}}>{fmtN(p.disc)}</td><td style={{padding:"7px 10px",textAlign:"right",color:T.mid}}>{fmtN(cm)}</td></tr>;})}<tr style={{borderTop:`2px solid ${T.accent}33`}}><td colSpan={2} style={{padding:"9px 10px",textAlign:"right",color:T.accent,fontWeight:700,fontSize:11}}>Terminal</td><td style={{padding:"9px 10px",textAlign:"right",color:T.dim}}>{fmtN(res.tv)}</td><td style={{padding:"9px 10px",textAlign:"right",color:T.accent,fontWeight:700}}>{fmtN(res.dtv)}</td><td style={{padding:"9px 10px",textAlign:"right",color:T.text,fontWeight:700}}>{fmtN(res.s+res.dtv)}</td></tr><tr style={{borderTop:`1px solid ${T.border}`}}><td colSpan={2} style={{padding:"9px 10px",textAlign:"right",color:T.red,fontWeight:700,fontSize:11}}>− Dette Nette / action</td><td colSpan={2}/><td style={{padding:"9px 10px",textAlign:"right",color:parseFloat(ndPS)>0?T.red:T.green,fontWeight:700}}>{parseFloat(ndPS)>0?"−":"+"}{fmtN(Math.abs(parseFloat(ndPS)||0))}</td></tr><tr style={{borderTop:`2px solid ${T.green}44`}}><td colSpan={2} style={{padding:"10px 10px",textAlign:"right",color:T.green,fontWeight:700,fontSize:13}}>= FAIR VALUE / action</td><td colSpan={2}/><td style={{padding:"10px 10px",textAlign:"right",color:T.green,fontWeight:700,fontSize:18}}>{fmtP(res.fv,cur)}</td></tr></tbody></table></div>}</Crd>
    </div>}

    {/* WATCHLIST */}
    {page===PG.WL&&<div style={{animation:"fadeIn .5s ease-out"}}>
      <div style={{textAlign:"center",padding:"40px 0 30px"}}><h2 style={{fontSize:26,fontWeight:700,margin:0}}>★ <span style={{color:T.accent}}>Watchlist</span></h2><p style={{color:T.dim,fontSize:13,marginTop:8}}>Vos actions en surveillance · Sauvegardée localement</p></div>
      {wl.length===0?<Crd C={T} style={{textAlign:"center",padding:40}}><div style={{fontSize:40,marginBottom:12}}>★</div><div style={{color:T.dim,fontSize:14}}>Votre watchlist est vide</div><div style={{color:T.dim,fontSize:12,marginTop:6}}>Analysez une action et cliquez « + Watchlist » pour l'ajouter</div><button onClick={reset} style={{marginTop:16,background:`linear-gradient(135deg,${T.accent},#7c3aed)`,border:"none",borderRadius:10,padding:"10px 24px",color:dark?"#05030e":"#fff",fontWeight:700,fontSize:13,cursor:"pointer",fontFamily:ff}}>Rechercher une action</button></Crd>:wl.map(w=><Crd C={T} key={w.ticker} style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div onClick={()=>load(w.ticker)} style={{flex:1,cursor:"pointer"}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontFamily:mono,fontWeight:700,fontSize:16,color:T.accent}}>{w.ticker}</span><span style={{fontSize:13,color:T.mid}}>{w.name?.substring(0,30)}</span></div><div style={{fontSize:10,color:T.dim,marginTop:4}}>Ajouté le {w.date} · Prix d'ajout : {fmtP(w.price,w.currency)}</div></div><div style={{display:"flex",gap:8}}><button onClick={()=>load(w.ticker)} style={{background:T.accentDim,border:"none",borderRadius:8,padding:"8px 14px",color:T.accent,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:ff}}>Analyser</button><button onClick={()=>rmWl(w.ticker)} style={{background:T.redDim,border:"none",borderRadius:8,padding:"8px 12px",color:T.red,fontSize:11,fontWeight:600,cursor:"pointer"}}>✕</button></div></Crd>)}
    </div>}

    {/* SUPERINVESTORS */}
    {page===PG.GU&&<div style={{animation:"fadeIn .5s ease-out"}}>
      <div style={{textAlign:"center",padding:"40px 0 30px"}}><h2 style={{fontSize:26,fontWeight:700,margin:0}}>👑 <span style={{color:T.accent}}>Superinvestors</span></h2><p style={{color:T.dim,fontSize:13,marginTop:8}}>Portefeuilles 13F publics des légendes de l'investissement</p></div>
      <Crd C={T} style={{marginBottom:20}}><input type="text" value={gS} onChange={e=>setGS(e.target.value)} placeholder="Rechercher un investisseur ou un ticker..." style={{width:"100%",boxSizing:"border-box",background:T.input,border:`1.5px solid ${T.inputBorder}`,borderRadius:12,color:T.text,fontSize:14,fontFamily:ff,padding:"12px 16px",outline:"none"}}/></Crd>
      {GURUS.filter(g=>{const q=gS.toLowerCase();return!q||g.name.toLowerCase().includes(q)||g.fund.toLowerCase().includes(q)||g.holdings.some(h=>h.toLowerCase().includes(q));}).map(g=><Crd C={T} key={g.name}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:12}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:44,height:44,borderRadius:12,background:T.accentDim,display:"flex",alignItems:"center",justifyContent:"center",fontSize:22}}>{g.img}</div><div><div style={{fontSize:16,fontWeight:700}}>{g.name}</div><div style={{fontSize:11,color:T.dim}}>{g.fund}</div></div></div><div style={{textAlign:"right"}}><div style={{fontSize:14,fontWeight:700,fontFamily:mono,color:T.accent}}>{g.value}</div><div style={{fontSize:10,color:T.dim}}>{g.holdings.length} positions</div></div></div><div style={{display:"flex",flexWrap:"wrap",gap:6}}>{g.holdings.map(h=><button key={h} onClick={()=>{if(h.length<=5&&!h.includes(" "))load(h);}} style={{background:T.input,border:`1px solid ${T.inputBorder}`,borderRadius:6,padding:"4px 10px",color:T.mid,fontSize:11,fontFamily:mono,fontWeight:600,cursor:h.length<=5?"pointer":"default",transition:"all .2s"}} onMouseOver={e=>{if(h.length<=5){e.target.style.borderColor=T.accent;e.target.style.color=T.accent;}}} onMouseOut={e=>{e.target.style.borderColor=T.inputBorder;e.target.style.color=T.mid;}}>{h}</button>)}</div></Crd>)}
    </div>}

    {/* SETTINGS */}
    {page===PG.SET&&<div style={{animation:"fadeIn .5s ease-out"}}>
      <div style={{textAlign:"center",padding:"40px 0 30px"}}><h2 style={{fontSize:26,fontWeight:700,margin:0}}>⚙ <span style={{color:T.accent}}>Réglages</span></h2></div>
      <Crd C={T}><div style={{fontSize:12,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:16}}>Thème d'affichage</div>
        <div style={{display:"flex",gap:12}}>
          {[{l:"Mode Sombre",v:true,icon:"🌙"},{l:"Mode Clair",v:false,icon:"☀️"},{l:"Auto",v:"auto",icon:"🔄"}].map(opt=>{
            const active=opt.v==="auto"?false:(opt.v===dark);
            return <button key={opt.l} onClick={()=>{if(opt.v==="auto"){const h=new Date().getHours();setDark(h>=21||h<8);localStorage.setItem("fh_theme","auto");}else{setDark(opt.v);}}} style={{flex:1,padding:"18px 12px",background:active?T.accentDim:T.input,border:`1.5px solid ${active?T.accent+"44":T.inputBorder}`,borderRadius:14,cursor:"pointer",textAlign:"center",transition:"all .2s"}}>
              <div style={{fontSize:28,marginBottom:6}}>{opt.icon}</div>
              <div style={{fontSize:13,fontWeight:600,color:active?T.accent:T.text}}>{opt.l}</div>
            </button>;
          })}
        </div>
      </Crd>
      <Crd C={T}><div style={{fontSize:12,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:12}}>Données</div><div style={{fontSize:13,color:T.mid,lineHeight:1.8}}>API : Finnhub.io (plan gratuit — 60 requêtes/minute)<br/>Portefeuilles : données 13F publiques (SEC EDGAR)<br/>Stockage watchlist : navigateur local (localStorage)</div></Crd>
    </div>}

    {/* ABOUT */}
    {page===PG.ABT&&<div style={{animation:"fadeIn .5s ease-out"}}>
      <div style={{textAlign:"center",padding:"40px 0 30px"}}><div style={{display:"inline-flex",marginBottom:16}}><div style={{width:56,height:56,borderRadius:16,background:`linear-gradient(135deg,${T.accent},#7c3aed)`,display:"flex",alignItems:"center",justifyContent:"center",boxShadow:`0 6px 30px ${T.accentGlow}`}}><Star size={32} color={dark?"#05030e":"#fff"}/></div></div><h2 style={{fontSize:26,fontWeight:700,margin:0}}>Fin<span style={{color:T.accent}}>heist</span></h2><p style={{color:T.dim,fontSize:13,marginTop:8}}>Intrinsic Value Engine</p></div>
      <Crd C={T}><div style={{fontSize:14,lineHeight:1.8,color:T.mid}}>Finheist est un outil d'analyse de valorisation intrinsèque par actualisation des flux de trésorerie (DCF). Conçu pour les investisseurs fondamentaux qui souhaitent estimer la valeur réelle d'une action à partir de ses cash flows futurs.<br/><br/>Données financières en temps réel via Finnhub.io. Consensus analystes intégré (buy/hold/sell + price targets). Portefeuilles de superinvestors (données 13F publiques SEC). Toutes métriques per share.<br/><br/>Gratuit et open source. Ceci n'est pas un conseil d'investissement.</div></Crd>
      <Crd C={T}><div style={{fontSize:12,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:14}}>Contact</div><textarea value={cMsg} onChange={e=>setCMsg(e.target.value)} rows={4} placeholder="Une remarque, suggestion ou question..." style={{width:"100%",boxSizing:"border-box",background:T.input,border:`1.5px solid ${T.inputBorder}`,borderRadius:12,color:T.text,fontSize:14,fontFamily:ff,padding:"14px 16px",outline:"none",resize:"vertical",marginBottom:12}}/><button onClick={()=>{if(cMsg.trim()){setCSent(true);setTimeout(()=>setCSent(false),3000);}}} style={{background:cSent?T.greenDim:`linear-gradient(135deg,${T.accent},#7c3aed)`,border:"none",borderRadius:10,padding:"12px 24px",color:cSent?T.green:dark?"#05030e":"#fff",fontWeight:700,fontSize:13,cursor:"pointer",fontFamily:ff}}>{cSent?"✓ Message envoyé":"Envoyer"}</button></Crd>
      <Crd C={T}><div style={{fontSize:12,fontWeight:600,color:T.dim,textTransform:"uppercase",letterSpacing:".1em",marginBottom:10}}>Crédits</div><div style={{fontSize:13,color:T.mid,lineHeight:1.8}}>Développé par <span style={{color:T.accent,fontWeight:600}}>Yanis Mendeng</span><br/>Données : Finnhub.io<br/>Portefeuilles : 13F publics (SEC)<br/>Hébergement : Vercel</div></Crd>
    </div>}

    <div style={{textAlign:"center",marginTop:40,fontSize:10,color:T.dim,lineHeight:1.7}}><Star size={14} color={T.dim}/><br/>Finheist · Intrinsic Value Engine<br/>Ceci n'est pas un conseil d'investissement.</div>
    </div></div></div>;
}
